### ISSUE TITLE
meson build dependencies

### ISSUE THREAD

**Issue by rmattes** [openAVproductions/openAV-Avtka#2]
What is  the 'benchmark' dependency in meson.build and where is it available?

**Comment by harryhaaren** [comment]
Hi, the benchmark library is Google-benchmark, it is often packaged by distros. Note that the performance testing of avtka is still in development, so it doesn't do much yet.

**Comment by rmattes** [comment]
>  it is often packaged by distros

Unfortunately, not in Debian.

>  it doesn't do much yet

It stops the meson build :-)  Even so I installed the benmark library (from  https://github.com/google/benchmark) meson can't find it.

**Comment by harryhaaren** [comment]
@rmattes - the above commit should solve the issue. I'll close this issue, but please re-open if it didn't solve it for you!
