### ISSUE TITLE
Example with lv2 integration

### ISSUE THREAD

**Issue by m4l3z** [openAVproductions/openAV-Avtka#4]
Hello there ! 
Could you make a basic example of how to use avtka in a lv2 context ? I'm really interested in trying it as I struggle a lot with choosing a toolkit.

**Comment by harryhaaren** [comment]
Hey M4l3z!

Good idea - I should try demo how to do that. Currently, there is no sample for that, and perhaps current code won't even allow that in **AVTKA**.

**AVTK** (note the missing A at the end) however has always already supported this - but has other limitations. Perhaps you already knew that - but just to be sure. ( https://github.com/openAVproductions/openAV-Avtk )

I probably won't get to work on that too soon - I'm attending Sonoj this weekend, and am travelling for work next week - so I'll be short on time. But do "ping" this issue in 2 or 3 weeks if I haven't popped something in by then!

Cheers -Harry

**Comment by m4l3z** [comment]
Yes I actually discovered AVTK first via your awesome talk at lac and noticed there was a C port which is perfect for me but I need some guidance. 
Alright, enjoy Sonoj, i'll ping you !
